name: Trigger Testing Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger testing repository
        uses: actions/checkout@v3
      # Add steps to trigger Testing repository workflow
