
name: Sync to Testing Repository

on:
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Developing Repository
        uses: actions/checkout@v3

      - name: Push Changes to Testing Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "sneha6396"
          git config --global user.email "ikuttisneha@gmail.com"
          git remote add testing https://<USERNAME>:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/<sneha6396>/<TESTING-REPO>.git
          git push testing main


